name: Build Typst document
  
on:
  push:
    branches:
      - main # Replace with the branch where the file is generated
jobs:
  build_typst_documents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: |
            Engineering/SoftwareEngineeringForDataScience/syllabus.typ
  
      - name: Configure Git
        run: |
          git config --local user.email "kazewong.physics@gmail.com"
          git config --local user.name "Kaze Wong"
  
      - name: Commit changes
        run: |
          git add -f **/*.pdf
          git commit -m "Add generated file"
          git checkout pdf
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
