name: Build Typst document
  
on:
  push:
    branches:
      - main # Replace with the branch where the file is generated
jobs:
  build_typst_documents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: |
            Engineering/SoftwareEngineeringForDataScience/syllabus.typ
  
      - name: Commit changes
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: pdf
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
