name: Build Typst document
  
on:
  push:
    branches:
      - main # Replace with the branch where the file is generated
jobs:
  build_typst_documents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: |
            Engineering/SoftwareEngineeringForDataScience/syllabus.typ
  
      - name: Checkout pdf branch
        uses: actions/checkout@v3
        with:
          ref: pdf
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -f **/*.pdf
          git commit -m "Add generated file"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
