name: Build Typst document
  
on:
  push:
    branches:
      - main # Replace with the branch where the file is generated
jobs:
  build_typst_documents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: |
            Engineering/SoftwareEngineeringForDataScience/syllabus.typ
            Engineering/SoftwareEngineeringForDataScience/lab/problemAnalysis.typ
            Engineering/SoftwareEngineeringForDataScience/lab/versionControl.typ
            Engineering/SoftwareEngineeringForDataScience/lab/python.typ
            Engineering/SoftwareEngineeringForDataScience/lab/julia.typ
            Engineering/SoftwareEngineeringForDataScience/lab/rust.typ
            Engineering/SoftwareEngineeringForDataScience/lab/jax.typ

      - name: MoveFiles
        run: |
          mkdir pdfs
          mv Engineering/SoftwareEngineeringForDataScience/syllabus.pdf pdfs/
          mv Engineering/SoftwareEngineeringForDataScience/lab/problemAnalysis.pdf pdfs/
          mv Engineering/SoftwareEngineeringForDataScience/lab/versionControl.pdf pdfs/
          mv Engineering/SoftwareEngineeringForDataScience/lab/python.pdf pdfs/
          mv Engineering/SoftwareEngineeringForDataScience/lab/julia.pdf pdfs/
          mv Engineering/SoftwareEngineeringForDataScience/lab/rust.pdf pdfs/
          mv Engineering/SoftwareEngineeringForDataScience/lab/jax.pdf pdfs/
  
      # Deploy to local repo
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: pdf
          FOLDER: pdfs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
